apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: http-echo
  name: http-echo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo
  namespace: http-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-echo
  template:
    metadata:
      labels:
        app: http-echo
    spec:
      containers:
      - name: http-echo
        image: antoniomarfer/http-echo
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: http-echo
  namespace: http-echo
spec:
  type: ClusterIP
  selector:
    app: http-echo
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080